### ISSUE TITLE
Missing Fields in friend.sql

### ISSUE THREAD

**Issue by 2kodes** [atk4/filestore#1]
Hello, 

I tried to run the demo and got the following error:
![atk4_filestore](https://user-images.githubusercontent.com/2084398/36340725-6695f0ae-13da-11e8-9653-4082fc88cb2a.png)

Even though the fields (file and file2 ) are part of the Frend model they are missing from the friend.sql. On adding the columns to the database manually there were no further errors.

**Comment by romaninsh** [comment]
cool, can please create a PR with the fix?

**Comment by romaninsh** [comment]
fixed.
