### ISSUE TITLE
atk4/ui 2.1 breaks code

### ISSUE THREAD

**Issue by mkrecek234** [atk4/filestore#16]
This does not work anymore:
`$this->addField('attachment', new \atk4\filestore\Field\File($this->app->filesystem));`

Error:
`Error: Class 'atk4\filestore\Model\Model' not found`

**Comment by mkrecek234** [comment]
This issue is present with 2.1 *after* you applied the PR #17 to make onHook/addHook refactoring already.

**Comment by mkrecek234** [comment]
This issue will be gone if you merge the in the meantime updated PR #17

**Comment by domainoverflow** [comment]
How ? Thanks

**Comment by domainoverflow** [comment]
I got onUpload to work. Trying to get onDelete now.  I am using it in a CRUD.

**Comment by mkrecek234** [comment]
Can you share this with us and push it to your fork? Or submit a PR? Thx!

**Comment by domainoverflow** [comment]
Yes sure I can share. I've never done a PR though ... I can push to my fork yes, would that do ?  Everything is working now except the onDelete when triggered from the form control ( the red x ). From the CRUD class is a problem because that breaks the update. The upload works nicely from the CRUD.

**Comment by mkrecek234** [comment]
Adressed by release 0.2.0
