### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by rapgithub** [atk4/filestore#4]
running
composer require atk4/filestore

error in the console:

Could not find a version of package atk4/filestore

```
 [InvalidArgumentException]                                                   
  Could not find a version of package atk4/filestore matching your minimum-st  
  ability (stable). Require it with an explicit version constraint allowing i  
  ts desired stability.                                                        
                          
```

**Comment by DarkSide666** [comment]
Can you show your composer.json file?

**Comment by rapgithub** [comment]
adding    "minimum-stability": "dev" and  "prefer-stable": false fix the issue with the installation!
```
{
  "minimum-stability": "dev",
  "prefer-stable": false,  
  "require":{
    "atk4/ui": "^1.2",
    "atk4/login": "^1.0",
    "atk4/filestore": "dev-master",
    "atk4/mastercrud": "dev-master"
  }
}
```

**Comment by DarkSide666** [comment]
Currently there are no releasesand no stable versions of this add-on so yes, minimum-stability should be dev.

**Comment by rapgithub** [comment]
thanks it should be stated in the installation as well this info!!! so it helps to another one trying to install it :)

**Comment by abbadon1334** [comment]
@DarkSide666 i think this can be closed?

**Comment by DarkSide666** [comment]
yes probably
