### ISSUE TITLE
Do not delete if other tokens refer to same location

### ISSUE THREAD

**Issue by mkrecek234** [atk4/filestore#46]
Situation:
- Sometimes you want to have one physical file which is referred to by multiple entities, for example you do a mass mailing with an attachment and have many email message entities which share the same attachment
- You would want them to attach via filestore with individual tokens, but with the same `location` field, so you do not have to store the attachment file e.g. 1000 times.
- Issue today: If one of those mass emails is deleted, filestore would delete the physical file `location` where then all other emails lose their file as well

Proposed solution:
- filestore will only delete the physical file, if there is no other entity in `file` model which refers to the same location. Otherwise the file will not be deleted.

Please share your thoughts, I could then submit a PR implementing this.

**Comment by mkrecek234** [comment]
Here is the context where this would be implemented: https://github.com/atk4/filestore/blob/1b7bdca2d579226e244a04dbfbd9416bb1e2a635/src/Model/File.php#L109

**Comment by DarkSide666** [comment]
Thanks for contribution!
